# Generated by Django 5.1.15 on 2026-10-08 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('JOB', 'Full-time Job'), ('INTERNSHIP', 'Internship')], default='JOB', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_or_stipend', models.CharField(help_text='e.g. 12 LPA or ₹30,000/month', max_length=150)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Target graduation year (leave blank if open to all batches)', null=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_branches', models.ManyToManyField(blank=True, related_name='job_postings', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
